spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service  # Service name registered in Eureka
          predicates:
            - Path=/users/**  # Ensure this path matches your API endpoint

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080  # API Gateway will run on port 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

