server:
  port: 8761  # Default port for the Eureka Server

eureka:
  client:
    register-with-eureka: false  # Since this is the Eureka Server itself, it doesn't need to register with another Eureka server
    fetch-registry: false  # No need to fetch registry data from other Eureka servers

  server:
    wait-time-in-ms-when-sync-empty: 0

spring:
  application:
    name: eureka-server

management:
  endpoints:
    web:
      exposure:
        include: "*"
